<?php
/**
 * The demo catalogue.
 *
 * Names, copy, specifications, brands, colourways, sizes, prices and
 * photography come from the Marketly reference application, so an imported
 * store shows real merchandise — footwear, outerwear, jewellery, electronics —
 * rather than placeholder shapes.
 *
 * Photography is hosted by Unsplash, whose licence permits commercial use
 * without attribution. The importer downloads each file into the media
 * library, so the store serves its own copies rather than hotlinking.
 *
 * @package Marketly_Core
 */

defined( 'ABSPATH' ) || exit;

/**
 * Product categories, in the order the strip shows them.
 *
 * @return array
 */
function marketly_demo_categories() {
	return array(
		array(
			'name'        => 'Electronics',
			'slug'        => 'electronics',
			'description' => 'Smartphones, laptops, headphones, smartwatches & tech gadgets.',
			'image'       => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
		),
		array(
			'name'        => 'Fashion',
			'slug'        => 'fashion',
			'description' => 'Trendy clothing, shoes, designer bags and accessories.',
			'image'       => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=400&q=80',
		),
		array(
			'name'        => 'Home & Decor',
			'slug'        => 'home',
			'description' => 'Modern furniture, ambient lighting, kitchenware and home accents.',
			'image'       => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=400&q=80',
		),
		array(
			'name'        => 'Beauty',
			'slug'        => 'beauty',
			'description' => 'Skincare, makeup, luxury fragrances and wellness essentials.',
			'image'       => 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=400&q=80',
		),
		array(
			'name'        => 'Grocery',
			'slug'        => 'grocery',
			'description' => 'Farm-fresh organic produce, gourmet coffee and everyday pantry.',
			'image'       => 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80',
		),
		array(
			'name'        => 'Sports',
			'slug'        => 'sports',
			'description' => 'Fitness equipment, workout gear, yoga accessories and sports apparel.',
			'image'       => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=400&q=80',
		),
	);
}

/**
 * The products.
 *
 * @return array
 */
function marketly_demo_products() {
	return array(
		array(
			'ref'         => 'prod-flash-1',
			'name'        => 'Ultra Smart Watch Series X with AMOLED Display',
			'slug'        => 'ultra-smart-watch-series-x',
			'category'    => 'Electronics',
			'price'       => 149.99,
			'regular'     => 249,
			'stock'       => 24,
			'rating'      => 4.9,
			'reviews'     => 3420,
			'description' => 'Next-generation smartwatch featuring an ultra-bright Always-On AMOLED sapphire display, ECG and continuous SpO2 heart tracking, GPS dual-frequency navigation, and 7-day battery life in a titanium finish.',
			'features'    => array( '1.96-inch Always-On Crystal AMOLED display', 'Advanced ECG, SpO2 & Body Composition sensors', '50m Water Resistant with automatic dive detection', 'Ultra-fast wireless charging (0 to 80% in 35 mins)', 'Dual-frequency GPS with precision route back' ),
			'specs'       => array(
				'Display'          => '1.96" AMOLED Sapphire Glass',
				'Battery Life'     => 'Up to 7 Days Normal Use',
				'Water Resistance' => '5 ATM / 50 Meters',
				'Case Material'    => 'Aerospace Grade Titanium',
				'Connectivity'     => 'Bluetooth 5.3, Wi-Fi, NFC, GPS',
			),
			'brand'       => 'Chronos Pro',
			'tags'        => array( 'smartwatch', 'fitness', 'tech', 'wearable' ),
			'colors'      => array( 'Midnight Black', 'Silver Titanium', 'Ocean Blue' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => true,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-feat-2',
			'name'        => 'Premium Wireless Earbuds Pro with Spatial Audio',
			'slug'        => 'premium-wireless-earbuds-pro',
			'category'    => 'Electronics',
			'price'       => 69.99,
			'regular'     => 99.99,
			'stock'       => 62,
			'rating'      => 4.8,
			'reviews'     => 2631,
			'description' => 'Immerse yourself in crystal clear audio with adaptive active noise cancellation, custom high-excursion low-distortion drivers, spatial audio with head tracking, and 36-hour total playback with MagSafe charging case.',
			'features'    => array( 'Active Noise Cancellation with Transparency Mode', 'Personalized Spatial Audio with dynamic head tracking', 'Sweat and water resistant (IPX4 rating)', 'Up to 6 hours listening time (36 hours with case)' ),
			'specs'       => array(
				'Driver'        => '11mm Custom Dynamic Driver',
				'Noise Control' => 'Hybrid ANC + Dual Beamforming Mics',
				'Battery'       => '6h ANC On / 36h Total with Case',
				'Connectivity'  => 'Bluetooth 5.3 + Fast Pair',
			),
			'brand'       => 'SonicAura',
			'tags'        => array( 'audio', 'earbuds', 'wireless', 'music' ),
			'colors'      => array( 'Pure White', 'Matte Black', 'Glacier Silver' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-best-1',
			'name'        => 'iPhone 15 Pro Max 256GB - Natural Titanium',
			'slug'        => 'iphone-15-pro-max-256gb',
			'category'    => 'Electronics',
			'price'       => 999.99,
			'regular'     => 1299.99,
			'stock'       => 18,
			'rating'      => 4.9,
			'reviews'     => 1200,
			'description' => 'Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, the most powerful iPhone camera system ever with 5x optical telephoto lens, and USB-C with USB 3 speeds.',
			'features'    => array( 'Strong and lightweight titanium design with textured matte glass', '6.7-inch Super Retina XDR display with ProMotion up to 120Hz', 'A17 Pro chip delivers next-level mobile gaming performance', '48MP Main camera with 5x optical zoom on the 120mm lens' ),
			'specs'       => array(
				'Display'   => '6.7-inch OLED 120Hz ProMotion',
				'Processor' => 'A17 Pro 3nm Chip',
				'Storage'   => '256GB High Speed NVMe',
				'Camera'    => '48MP Main + 12MP Ultra-Wide + 12MP 5x Telephoto',
			),
			'brand'       => 'Apple',
			'tags'        => array( 'smartphone', 'apple', 'ios', 'mobile' ),
			'colors'      => array( 'Black Titanium', 'Natural Titanium', 'White Titanium', 'Blue Titanium' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-best-2',
			'name'        => 'MacBook Air M2 13.6-inch Liquid Retina Display',
			'slug'        => 'macbook-air-m2-13-inch',
			'category'    => 'Electronics',
			'price'       => 1099.99,
			'regular'     => 1349.99,
			'stock'       => 22,
			'rating'      => 4.9,
			'reviews'     => 1200,
			'description' => 'Redesigned around the next-generation M2 chip, MacBook Air is strikingly thin and brings exceptional speed and power efficiency inside an all-aluminum enclosure. Up to 18 hours of battery life.',
			'features'    => array( 'Supercharged by the next-generation M2 8-core CPU and 10-core GPU', '13.6-inch Liquid Retina display with 500 nits brightness and P3 wide color', '1080p FaceTime HD camera, three-mic array, and four-speaker sound system', 'MagSafe 3 charging port, two Thunderbolt ports, and headphone jack' ),
			'specs'       => array(
				'Processor'        => 'Apple M2 Chip (8-core CPU, 10-core GPU)',
				'Memory & Storage' => '16GB Unified RAM, 512GB SSD',
				'Display'          => '13.6" Liquid Retina (2560x1664)',
				'Weight'           => '2.7 lbs (1.24 kg)',
			),
			'brand'       => 'Apple',
			'tags'        => array( 'laptop', 'macbook', 'apple', 'computer' ),
			'colors'      => array( 'Midnight', 'Starlight', 'Space Gray', 'Silver' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-elec-3',
			'name'        => 'Sony Alpha A7 IV Full-Frame Mirrorless Camera',
			'slug'        => 'sony-alpha-a7-iv-mirrorless-camera',
			'category'    => 'Electronics',
			'price'       => 1899,
			'regular'     => 2299,
			'stock'       => 3,
			'rating'      => 4.9,
			'reviews'     => 840,
			'description' => '33MP full-frame Exmor R back-illuminated CMOS sensor with BIONZ XR processing engine. 4K 60p 10-bit 4:2:2 video recording and real-time Eye AF for birds, animals, and humans.',
			'features'    => array( '33MP Full-Frame Exmor R Back-Illuminated CMOS Sensor', '759-point phase-detection autofocus with 94% frame coverage', '4K 60p video in 10-bit 4:2:2 with S-Cinetone color profile', '5.5-step 5-axis in-body optical image stabilization' ),
			'specs'       => array(
				'Sensor Size'  => '35.9 x 23.9 mm (Full Frame)',
				'ISO Range'    => '100-51,200 (Expandable to 50-204,800)',
				'Video Format' => 'XAVC S / XAVC HS 10-bit 4:2:2',
				'Mount'        => 'Sony E-Mount',
			),
			'brand'       => 'Sony',
			'tags'        => array( 'camera', 'photography', 'video', 'mirrorless' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-elec-4',
			'name'        => '34" Curved UltraWide QD-OLED 175Hz Gaming Monitor',
			'slug'        => 'curved-ultrawide-qd-oled-gaming-monitor',
			'category'    => 'Electronics',
			'price'       => 799.99,
			'regular'     => 1099.99,
			'stock'       => 14,
			'rating'      => 4.8,
			'reviews'     => 650,
			'description' => 'Breathtaking Quantum Dot OLED panel with true 0.03ms response time, 175Hz refresh rate, HDR True Black 400, and an immersive 1800R curve for esports and cinematic productivity.',
			'features'    => array( 'Quantum Dot OLED with infinite contrast and pure blacks', 'Ultra-fast 0.03ms GtG response time with 175Hz refresh rate', '99.3% DCI-P3 cinematic color gamut factory calibrated', '1800R curved ultra-wide 21:9 aspect ratio' ),
			'specs'       => array(
				'Resolution'   => '3440 x 1440 WQHD (21:9)',
				'Refresh Rate' => '175Hz with G-Sync / FreeSync',
				'Brightness'   => '1000 nits peak HDR',
				'Ports'        => '2x DP 1.4, 1x HDMI 2.1, 4x USB 3.2 Hub',
			),
			'brand'       => 'AlienVision',
			'tags'        => array( 'monitor', 'gaming', 'oled', 'display' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => true,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-elec-5',
			'name'        => 'Studio Wireless Over-Ear Active Noise Cancelling Headphones',
			'slug'        => 'studio-wireless-over-ear-anc-headphones',
			'category'    => 'Electronics',
			'price'       => 189.99,
			'regular'     => 279.99,
			'stock'       => 40,
			'rating'      => 4.7,
			'reviews'     => 1840,
			'description' => 'High-fidelity audio with custom-tuned 40mm beryllium drivers, 45 hours of battery life, plush memory foam ear cushions, and lossless audio streaming over USB-C or Bluetooth 5.3.',
			'features'    => array( 'Hybrid Adaptive Active Noise Cancellation with 4 mics', '45 hours of continuous wireless playback on a single charge', 'Ultra-soft protein leather memory foam ear cups', 'Multipoint connection seamlessly swaps between phone and laptop' ),
			'specs'       => array(
				'Driver'  => '40mm Custom Beryllium Driver',
				'Battery' => '45 Hours (ANC On) / Fast Charge',
				'Weight'  => '250g Lightweight Ergonomic',
			),
			'brand'       => 'SonicAura',
			'tags'        => array( 'headphones', 'audio', 'anc', 'wireless' ),
			'colors'      => array( 'Matte Black', 'Silver Cloud', 'Midnight Navy' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-elec-6',
			'name'        => 'Smart Home Voice Assistant Speaker with Hi-Fi Audio',
			'slug'        => 'smart-home-voice-assistant-speaker',
			'category'    => 'Electronics',
			'price'       => 79.99,
			'regular'     => 119.99,
			'stock'       => 50,
			'rating'      => 4.6,
			'reviews'     => 920,
			'description' => 'Control your smart home with high-accuracy far-field microphones and room-filling 360-degree acoustic fidelity with deep punchy bass.',
			'features'    => array( '360-degree spatial acoustic dispersion design', 'Built-in Matter & Zigbee smart home hub', 'Far-field 4-mic array with physical mute switch' ),
			'specs'       => array(
				'Power'        => '30W RMS High Efficiency Amp',
				'Connectivity' => 'Wi-Fi 6, Bluetooth 5.2, Thread',
			),
			'brand'       => 'NexusHome',
			'tags'        => array( 'speaker', 'smart-home', 'audio', 'iot' ),
			'colors'      => array( 'Chalk White', 'Charcoal Black' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-elec-7',
			'name'        => 'Mechanical RGB Hot-Swappable Wireless Keyboard',
			'slug'        => 'mechanical-rgb-wireless-keyboard',
			'category'    => 'Electronics',
			'price'       => 119.99,
			'regular'     => 159.99,
			'stock'       => 35,
			'rating'      => 4.8,
			'reviews'     => 710,
			'description' => 'Custom gasket-mounted 75% wireless mechanical keyboard with factory-lubed pre-installed linear switches, south-facing per-key RGB, and aluminum CNC chassis.',
			'features'    => array( 'Hot-swappable 5-pin PCB supports all MX-style switches', 'Tri-mode connectivity: 2.4GHz Wireless, Bluetooth 5.1, USB-C', 'Sound-dampening silicone gaskets and IXPE switch pads' ),
			'specs'       => array(
				'Layout'  => '75% Compact (82 Keys)',
				'Battery' => '4000mAh Lithium Rechargeable',
				'Keycaps' => 'Double-Shot PBT Cherry Profile',
			),
			'brand'       => 'KeyForge',
			'tags'        => array( 'keyboard', 'gaming', 'pc', 'accessories' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-feat-1',
			'name'        => 'Men\'s Air Sneakers Cushioned Running Shoes',
			'slug'        => 'mens-air-sneakers-running-shoes',
			'category'    => 'Fashion',
			'price'       => 59.99,
			'regular'     => 79.99,
			'stock'       => 45,
			'rating'      => 4.7,
			'reviews'     => 1234,
			'description' => 'Engineered for lightweight agility and maximum all-day shock absorption. Features breathable stretch mesh, high-rebound cushioning foam, and anti-slip grooved rubber traction outsole.',
			'features'    => array( 'Responsive cloud-cushion responsive midsole', 'Seamless engineered breathable mesh upper', 'Ortholite antimicrobial cushioned insole', 'High-abrasion durable rubber sole' ),
			'specs'       => array(
				'Upper Material' => 'Engineered Air Mesh',
				'Sole Material'  => 'Responsive EVA & Gum Rubber',
				'Closure'        => 'Lace-Up',
				'Arch Support'   => 'Neutral / High',
			),
			'brand'       => 'AeroStep',
			'tags'        => array( 'shoes', 'sneakers', 'running', 'sportswear' ),
			'colors'      => array( 'Triple White', 'Core Black', 'Vibrant Red' ),
			'sizes'       => array( 'US 8', 'US 9', 'US 10', 'US 11', 'US 12' ),
			'image'       => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-fash-2',
			'name'        => 'Signature Structured Saffiano Leather Tote Handbag',
			'slug'        => 'signature-structured-leather-tote-handbag',
			'category'    => 'Fashion',
			'price'       => 129.99,
			'regular'     => 189.99,
			'stock'       => 2,
			'rating'      => 4.9,
			'reviews'     => 780,
			'description' => 'Crafted from full-grain Italian saffiano leather with polished gold-tone hardware. Includes removable shoulder strap, padded 14-inch laptop divider, and multiple organizer pockets.',
			'features'    => array( 'Scratch and water-resistant genuine saffiano leather', 'Fits up to 14" laptop with protective interior padding', 'Custom gold-tone protective metal feet and hardware', 'Dual top carrying handles + adjustable crossbody strap' ),
			'specs'       => array(
				'Dimensions' => '14.5" W x 11" H x 5.5" D',
				'Material'   => 'Full Grain Saffiano Cowhide Leather',
				'Hardware'   => '14k Gold Plated Zinc Alloy',
			),
			'brand'       => 'Maison Luxe',
			'tags'        => array( 'handbag', 'fashion', 'luxury', 'leather' ),
			'colors'      => array( 'Beige Champagne', 'Caramel Tan', 'Noir Black' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-fash-3',
			'name'        => 'Classic Tailored Beige Utility Linen Overshirt',
			'slug'        => 'classic-tailored-beige-utility-overshirt',
			'category'    => 'Fashion',
			'price'       => 64.99,
			'regular'     => 85,
			'stock'       => 35,
			'rating'      => 4.6,
			'reviews'     => 410,
			'description' => 'Relaxed fit overshirt woven from breathable organic French flax linen blend. Double chest cargo pockets with horn buttons make it a versatile layering piece for all seasons.',
			'features'    => array( 'Pre-washed pure linen blend for soft broken-in feel', 'Reinforced dual utility chest patch pockets', 'Natural biodegradable faux horn buttons' ),
			'specs'       => array(
				'Composition' => '70% Organic Linen, 30% Cotton',
				'Fit'         => 'Relaxed Overshirt Fit',
				'Care'        => 'Machine Wash Cold, Hang Dry',
			),
			'brand'       => 'AeroStep',
			'tags'        => array( 'jacket', 'fashion', 'summer', 'linen' ),
			'colors'      => array( 'Sand Beige', 'Olive Drab', 'Navy Blue' ),
			'sizes'       => array( 'S', 'M', 'L', 'XL' ),
			'image'       => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-fash-4',
			'name'        => '100% Mongolian Cashmere Crewneck Sweater',
			'slug'        => 'mongolian-cashmere-crewneck-sweater',
			'category'    => 'Fashion',
			'price'       => 119.99,
			'regular'     => 169.99,
			'stock'       => 28,
			'rating'      => 4.9,
			'reviews'     => 520,
			'description' => 'Spun from Grade-A 2-ply pure Mongolian cashmere. Incredibly lightweight yet provides three times the insulating warmth of standard wool with zero itchiness.',
			'features'    => array( 'Grade-A 100% pure Mongolian long-staple cashmere', 'Ribbed neckline, cuffs, and hem with reinforced recovery', 'Pill-resistant tight gauge knitting' ),
			'specs'       => array(
				'Gauge' => '12 Gauge 2-Ply Cashmere',
				'Care'  => 'Hand Wash Cold or Dry Clean',
			),
			'brand'       => 'Maison Luxe',
			'tags'        => array( 'sweater', 'cashmere', 'luxury', 'apparel' ),
			'colors'      => array( 'Cream Heather', 'Charcoal Melange', 'Camel' ),
			'sizes'       => array( 'S', 'M', 'L', 'XL' ),
			'image'       => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-fash-5',
			'name'        => 'Minimalist Bauhaus Chronograph Mesh Watch',
			'slug'        => 'minimalist-bauhaus-chronograph-mesh-watch',
			'category'    => 'Fashion',
			'price'       => 89.99,
			'regular'     => 139.99,
			'stock'       => 32,
			'rating'      => 4.8,
			'reviews'     => 680,
			'description' => 'Clean Scandinavian aesthetic with ultra-slim 7mm case profile, Japanese Miyota quartz movement, scratch-proof sapphire crystal, and magnetic Milanese mesh band.',
			'features'    => array( 'Ultra-thin 316L stainless steel 40mm casing', 'Scratch-resistant domed sapphire crystal lens', 'Interchangeable quick-release Milanese loop strap' ),
			'specs'       => array(
				'Movement'         => 'Japanese Quartz Chronograph',
				'Water Resistance' => '30 Meters (3 ATM)',
			),
			'brand'       => 'Chronos Pro',
			'tags'        => array( 'watch', 'minimalist', 'accessories' ),
			'colors'      => array( 'Rose Gold', 'Silver Steel', 'Matte Black' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-fash-6',
			'name'        => 'Polarized Aviator Acetate UV400 Sunglasses',
			'slug'        => 'polarized-aviator-acetate-sunglasses',
			'category'    => 'Fashion',
			'price'       => 49.99,
			'regular'     => 79.99,
			'stock'       => 45,
			'rating'      => 4.7,
			'reviews'     => 890,
			'description' => 'Handcrafted Italian Mazzucchelli acetate frames paired with high-definition polarized triacetate cellulose lenses for complete glare elimination and 100% UVA/UVB protection.',
			'features'    => array( 'HD Polarized TAC lenses with anti-reflective back coating', 'Hand-polished Italian acetate frame with stainless wire core', 'Includes hard magnetic leather case and microfiber pouch' ),
			'specs'       => array(
				'Lens Width' => '54 mm',
				'UV Rating'  => '100% UV400 Protection',
			),
			'brand'       => 'AeroStep',
			'tags'        => array( 'sunglasses', 'eyewear', 'summer', 'fashion' ),
			'colors'      => array( 'Tortoise Shell', 'Gloss Black', 'Smoky Crystal' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => true,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-fash-7',
			'name'        => 'Handcrafted Genuine Leather Chelsea Boots',
			'slug'        => 'handcrafted-leather-chelsea-boots',
			'category'    => 'Fashion',
			'price'       => 145,
			'regular'     => 195,
			'stock'       => 20,
			'rating'      => 4.9,
			'reviews'     => 470,
			'description' => 'Classic British heritage ankle boot with Goodyear-welted construction, supple full-grain waxed leather upper, elasticated side gussets, and cushioned memory foam footbed.',
			'features'    => array( 'Goodyear welt construction enables resoling for longevity', 'Full-grain waxed oil leather develops rich patina over time', 'Durable studded rubber traction outsole' ),
			'specs'       => array(
				'Upper' => 'Full-Grain Waxed Cowhide',
				'Sole'  => 'Dainite Rubber Lug',
			),
			'brand'       => 'Maison Luxe',
			'tags'        => array( 'boots', 'footwear', 'leather', 'shoes' ),
			'colors'      => array( 'Cognac Brown', 'Obsidian Black' ),
			'sizes'       => array( 'US 8', 'US 9', 'US 10', 'US 11' ),
			'image'       => 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-fash-8',
			'name'        => 'High-Waist Sculpting Seamless Active Leggings',
			'slug'        => 'high-waist-sculpting-seamless-leggings',
			'category'    => 'Fashion',
			'price'       => 38,
			'regular'     => 55,
			'stock'       => 50,
			'rating'      => 4.8,
			'reviews'     => 930,
			'description' => 'Four-way stretch buttery soft compression fabric with a 4.5-inch ribbed tummy control waistband and zero front seam for unmatched squat-proof comfort.',
			'features'    => array( '100% Squat-proof ultra-opaque technical fabric', 'Ribbed high waistband prevents rolling down', 'Moisture-wicking quick-dry antimicrobial finish' ),
			'specs'       => array(
				'Material' => '80% Nylon, 20% Spandex',
				'Inseam'   => '28 inches (Full Length)',
			),
			'brand'       => 'AeroStep',
			'tags'        => array( 'leggings', 'activewear', 'fitness', 'yoga' ),
			'colors'      => array( 'Deep Espresso', 'Midnight Teal', 'Onyx Black' ),
			'sizes'       => array( 'XS', 'S', 'M', 'L' ),
			'image'       => 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-best-4',
			'name'        => 'Modern 3-Seater High-Resilience Fabric Sofa',
			'slug'        => 'modern-3-seater-fabric-sofa',
			'category'    => 'Home & Decor',
			'price'       => 299.99,
			'regular'     => 379.99,
			'stock'       => 4,
			'rating'      => 4.6,
			'reviews'     => 542,
			'description' => 'A contemporary silhouette meets luxurious comfort. Upholstered in stain-resistant textured woven fabric with high-resilience foam cushions and a solid kiln-dried hardwood frame for lifetime durability.',
			'features'    => array( 'Stain-resistant, pet-friendly high performance linen-blend fabric', 'Reinforced kiln-dried FSC-certified solid oak inner frame', 'Reversible high-density multi-layer pocket spring cushions', 'Easy tool-free 10-minute assembly' ),
			'specs'       => array(
				'Dimensions'      => '84" W x 35" D x 33" H',
				'Seat Depth'      => '23.5 inches',
				'Weight Capacity' => '850 lbs (385 kg)',
				'Upholstery'      => 'Premium Woven Heather Fabric',
			),
			'brand'       => 'NordicHaven',
			'tags'        => array( 'furniture', 'sofa', 'living-room', 'decor' ),
			'colors'      => array( 'Charcoal Slate', 'Oatmeal Beige', 'Emerald Forest' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-best-3',
			'name'        => 'Air Fryer 4.5L Digital Touchscreen with 8 Presets',
			'slug'        => 'air-fryer-4-5l-digital-display',
			'category'    => 'Home & Decor',
			'price'       => 75.99,
			'regular'     => 99.99,
			'stock'       => 39,
			'rating'      => 4.7,
			'reviews'     => 862,
			'description' => 'Enjoy guilt-free crispy meals with 360° rapid air circulation technology. Requires up to 85% less oil than traditional deep frying. Features 8 one-touch cooking presets and dishwasher-safe non-stick basket.',
			'features'    => array( '4.5 Litre capacity ideal for 3-5 person families', 'One-touch intuitive digital LED touchscreen with 8 presets', 'Rapid 360° air heat circulation up to 200°C / 400°F', 'PFOA-free & BPA-free dishwasher-safe non-stick basket' ),
			'specs'       => array(
				'Capacity'          => '4.5 Liters',
				'Power'             => '1500 Watts',
				'Temperature Range' => '80°C - 200°C (175°F - 400°F)',
				'Timer'             => '1 - 60 minutes with auto-shutoff',
			),
			'brand'       => 'CuisineMaster',
			'tags'        => array( 'kitchen', 'appliance', 'cooking', 'healthy' ),
			'colors'      => array( 'Matte Black', 'Stainless Pearl' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-home-3',
			'name'        => 'Scandinavian Minimalist Dimmable Pendant Chandelier',
			'slug'        => 'scandinavian-minimalist-pendant-chandelier',
			'category'    => 'Home & Decor',
			'price'       => 89,
			'regular'     => 135,
			'stock'       => 25,
			'rating'      => 4.8,
			'reviews'     => 430,
			'description' => 'Handcrafted brushed aluminum and spun matte ceramic dome fixture. Projects warm ambient downward glow perfect for dining islands, living rooms, and bedroom decor.',
			'features'    => array( 'Integrated flicker-free warm 2700K-4000K dimmable LED', 'Adjustable 150cm woven fabric suspension cord', 'Energy-saving A++ certified low wattage power draw' ),
			'specs'       => array(
				'Diameter'     => '38 cm (15 inches)',
				'Lumen Output' => '1200 Lumens CRI 95+',
			),
			'brand'       => 'NordicHaven',
			'tags'        => array( 'lighting', 'chandelier', 'scandinavian', 'decor' ),
			'colors'      => array( 'Matte White', 'Brushed Brass', 'Nordic Grey' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-home-4',
			'name'        => 'Artisan Ceramic Pour-Over Goose-Neck Kettle Set',
			'slug'        => 'artisan-ceramic-pour-over-kettle-set',
			'category'    => 'Home & Decor',
			'price'       => 49.99,
			'regular'     => 69.99,
			'stock'       => 30,
			'rating'      => 4.9,
			'reviews'     => 780,
			'description' => 'Precision gooseneck spout for controlled spiral water flow extraction. Includes matching grooved ceramic dripper and heat-resistant borosilicate glass carafe.',
			'features'    => array( 'Precision flow-rate gooseneck spout for optimal coffee bloom', 'High-fired ceramic dripper maintains ideal brew temperature', 'Real walnut wood ergonomic heat-resistant handle' ),
			'specs'       => array(
				'Capacity' => '800ml (27 fl oz)',
				'Material' => '304 Stainless Steel + Ceramic Carafe',
			),
			'brand'       => 'CuisineMaster',
			'tags'        => array( 'coffee', 'kitchenware', 'pourover', 'dining' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-home-5',
			'name'        => 'Handcrafted Solid Acacia Wood Charcuterie Board',
			'slug'        => 'handcrafted-solid-acacia-charcuterie-board',
			'category'    => 'Home & Decor',
			'price'       => 34.5,
			'regular'     => 49,
			'stock'       => 45,
			'rating'      => 4.8,
			'reviews'     => 390,
			'description' => 'Carved from single-piece sustainably harvested organic acacia hardwood. Features rich natural grain patterns, beveled juice grooves, and brass hanging ring.',
			'features'    => array( '100% natural organic Acacia hardwood food-grade mineral oiled', 'Reversible design with deep perimeter juice drainage canal', 'Resistant to blade scarring and moisture absorption' ),
			'specs'       => array(
				'Dimensions' => '18" L x 12" W x 0.8" Thick',
				'Weight'     => '1.4 kg (3.1 lbs)',
			),
			'brand'       => 'NordicHaven',
			'tags'        => array( 'kitchen', 'woodwork', 'dining', 'entertaining' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-home-6',
			'name'        => 'Ultrasonic Ceramic Essential Oil Aroma Diffuser (300ml)',
			'slug'        => 'ultrasonic-ceramic-aroma-diffuser',
			'category'    => 'Home & Decor',
			'price'       => 44.99,
			'regular'     => 65,
			'stock'       => 35,
			'rating'      => 4.9,
			'reviews'     => 610,
			'description' => 'Matte handcrafted ceramic cover with whisper-quiet 2.4MHz ultrasonic mist vaporization. Includes 7 ambient warm lighting modes and waterless safety auto shut-off.',
			'features'    => array( 'Handcrafted natural bisque porcelain ceramic shell', 'Ultra-silent (<20dB) operation for deep sleep and focus', 'Covers up to 400 sq. ft with 10-hour continuous runtime' ),
			'specs'       => array(
				'Tank Capacity' => '300ml BPA-Free Reservoir',
				'Timer Modes'   => '1H / 3H / 6H / Continuous',
			),
			'brand'       => 'NordicHaven',
			'tags'        => array( 'diffuser', 'aromatherapy', 'wellness', 'decor' ),
			'colors'      => array( 'Bisque White', 'Terra Cotta', 'Charcoal Slate' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-home-7',
			'name'        => 'Ergonomic Breathable Mesh Executive Office Chair',
			'slug'        => 'ergonomic-breathable-mesh-office-chair',
			'category'    => 'Home & Decor',
			'price'       => 219,
			'regular'     => 299,
			'stock'       => 16,
			'rating'      => 4.8,
			'reviews'     => 420,
			'description' => 'Engineered for 12+ hour ergonomic support with adaptive dynamic lumbar tracking, 3D adjustable armrests, 135° tilt recline lock, and reinforced Korean mesh.',
			'features'    => array( 'Adaptive auto-following lumbar spinal support', '3D multidirectional padded armrests with height adjustment', 'Heavy-duty class-4 SGS certified explosion-proof gas lift cylinder' ),
			'specs'       => array(
				'Weight Capacity' => '330 lbs (150 kg)',
				'Recline Angle'   => '90° - 135° Synchronous Tilt',
			),
			'brand'       => 'NordicHaven',
			'tags'        => array( 'chair', 'office', 'ergonomic', 'furniture' ),
			'colors'      => array( 'Onyx Black', 'Space Grey' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1580481077194-436f56477e38?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-home-8',
			'name'        => '100% Washed French Flax Linen Duvet Cover Set',
			'slug'        => 'washed-french-flax-linen-duvet-set',
			'category'    => 'Home & Decor',
			'price'       => 139,
			'regular'     => 189,
			'stock'       => 22,
			'rating'      => 4.9,
			'reviews'     => 310,
			'description' => 'Woven from 100% premium certified Normandy French flax linen. Pre-stone-washed for incredible softness and year-round thermo-regulating breathability.',
			'features'    => array( 'Naturally hypoallergenic, breathable, and temperature-regulating', 'Gets softer with every machine wash', 'Includes 1 Duvet Cover + 2 Matching Pillow Shams with coconut shell buttons' ),
			'specs'       => array(
				'Size'     => 'Queen / King',
				'Material' => '100% French Flax Linen (170 GSM)',
			),
			'brand'       => 'NordicHaven',
			'tags'        => array( 'bedding', 'linen', 'bedroom', 'decor' ),
			'colors'      => array( 'Oatmeal Dune', 'Olive Sage', 'Misty Grey' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-beauty-1',
			'name'        => 'Luxe Botanical Skin Renewal Serum & Elixir Set',
			'slug'        => 'luxe-botanical-skin-renewal-serum',
			'category'    => 'Beauty',
			'price'       => 42.5,
			'regular'     => 65,
			'stock'       => 75,
			'rating'      => 4.8,
			'reviews'     => 940,
			'description' => 'Enriched with cold-pressed botanical squalane, hyaluronic acid 2%, and stabilized Vitamin C for radiant glowing skin. Diminishes fine lines and locks in deep 24-hour hydration.',
			'features'    => array( '100% Vegan, Cruelty-free & Paraben-free formula', 'Dual-action Vitamin C + Hyaluronic Acid moisture lock', 'Dermatologist tested and approved for sensitive skin' ),
			'specs'       => array(
				'Volume'          => '50ml / 1.7 fl. oz',
				'Skin Type'       => 'All Skin Types (Sensitive Safe)',
				'Key Ingredients' => 'Vitamin C, Niacinamide, Botanical Squalane',
			),
			'brand'       => 'Botanica Pure',
			'tags'        => array( 'skincare', 'serum', 'beauty', 'glow' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1608248597359-46726154181a?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-beauty-2',
			'name'        => 'Velvet Matte Long-Wear Lipstick Collection (6 Shades)',
			'slug'        => 'velvet-matte-long-wear-lipstick',
			'category'    => 'Beauty',
			'price'       => 28,
			'regular'     => 38,
			'stock'       => 88,
			'rating'      => 4.7,
			'reviews'     => 1450,
			'description' => 'Ultra-pigmented, feather-light velvet matte lipstick that glides effortlessly on lips, offering up to 16 hours of transfer-proof rich coverage with nourishing shea butter.',
			'features'    => array( '16-hour smudge-proof velvety matte finish', 'Infused with Vitamin E and organic jojoba oil', 'Intense one-swipe color payoff' ),
			'specs'       => array(
				'Finish'        => 'Velvet Matte',
				'Weight'        => '3.8g each',
				'Certification' => 'Cruelty-Free Leaping Bunny Certified',
			),
			'brand'       => 'Maison Glow',
			'tags'        => array( 'makeup', 'lipstick', 'cosmetics' ),
			'colors'      => array( 'Ruby Romance', 'Nude Elegance', 'Plum Passion', 'Rose Petal' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-beauty-3',
			'name'        => 'Artisan Bergamot & Amber Eau De Parfum (100ml)',
			'slug'        => 'artisan-bergamot-amber-eau-de-parfum',
			'category'    => 'Beauty',
			'price'       => 78,
			'regular'     => 110,
			'stock'       => 35,
			'rating'      => 4.9,
			'reviews'     => 620,
			'description' => 'An alluring, bespoke unisex fragrance opening with bright Calabrian bergamot, transitioning into spicy cardamom and settled into warm amber resin and Haitian vetiver.',
			'features'    => array( 'Concentrated 22% Eau De Parfum formulation for 12+ hour sillage', 'Handcrafted with sustainably sourced essential oils', 'Heavy French crystal glass flacon with magnetic cap' ),
			'specs'       => array(
				'Volume'     => '100ml / 3.4 fl. oz',
				'Top Notes'  => 'Calabrian Bergamot, Pink Peppercorn',
				'Base Notes' => 'Warm Amber, Cedarwood, Vetiver',
			),
			'brand'       => 'Maison Glow',
			'tags'        => array( 'perfume', 'fragrance', 'luxury', 'beauty' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-beauty-4',
			'name'        => '24K Gold Snail Firming Radiance Night Cream',
			'slug'        => '24k-gold-snail-firming-night-cream',
			'category'    => 'Beauty',
			'price'       => 36.99,
			'regular'     => 52,
			'stock'       => 42,
			'rating'      => 4.8,
			'reviews'     => 710,
			'description' => 'Formulated with real 24-karat gold flakes and 85% filtered snail mucin to stimulate natural collagen regeneration, restore skin firmness, and brighten dark spots overnight.',
			'features'    => array( 'Infused with 99.9% pure 24K colloidal gold flakes', 'Triple peptide complex restores cellular elasticity', 'Lightweight non-greasy absorption for intensive night renewal' ),
			'specs'       => array(
				'Volume'      => '60g / 2.1 oz',
				'Application' => 'Nightly Facial Treatment',
			),
			'brand'       => 'Botanica Pure',
			'tags'        => array( 'anti-aging', 'skincare', 'gold', 'moisturizer' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-beauty-5',
			'name'        => 'Sonic Deep-Pore Silicone Facial Cleansing Device',
			'slug'        => 'sonic-silicone-facial-cleansing-device',
			'category'    => 'Beauty',
			'price'       => 39.99,
			'regular'     => 59.99,
			'stock'       => 60,
			'rating'      => 4.7,
			'reviews'     => 540,
			'description' => 'Delivers 8,000 T-Sonic pulsations per minute through ultra-hygienic soft silicone touchpoints to remove 99.5% of dirt, oil, and makeup residue without damaging delicate skin barriers.',
			'features'    => array( '8 adjustable vibration intensity speeds with memory', '100% waterproof IPX7 rating for shower use', 'Up to 300 uses on a single USB magnetic charge' ),
			'specs'       => array(
				'Material'     => 'Food-Grade Antibacterial Silicone',
				'Battery Life' => 'Up to 6 Months per Charge',
			),
			'brand'       => 'Maison Glow',
			'tags'        => array( 'beauty-device', 'cleanser', 'skincare', 'tech' ),
			'colors'      => array( 'Blush Pink', 'Mint Green', 'Lavender' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => true,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-groc-1',
			'name'        => 'Organic Farm Fresh Seasonal Fruit & Produce Basket',
			'slug'        => 'organic-farm-fresh-fruit-basket',
			'category'    => 'Grocery',
			'price'       => 34.99,
			'regular'     => 45,
			'stock'       => 30,
			'rating'      => 4.9,
			'reviews'     => 780,
			'description' => 'Hand-picked organic fruits and vegetables harvested directly from local sustainable farms. Guaranteed 100% pesticide-free, packed in eco-friendly biodegradable woven packaging.',
			'features'    => array( 'USDA Certified Organic & Non-GMO Project Verified', 'Harvested within 24 hours of delivery for peak crispness', 'Rich in vitamins, essential antioxidants, and enzymes' ),
			'specs'       => array(
				'Weight'     => 'approx. 5.5 kg (12 lbs)',
				'Origin'     => 'Local Certified Organic Cooperatives',
				'Shelf Life' => '7-10 days refrigerated',
			),
			'brand'       => 'GreenHarvest',
			'tags'        => array( 'organic', 'fruit', 'grocery', 'farm-fresh' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-groc-2',
			'name'        => 'Artisan Single-Origin Ethiopian Medium Roast Coffee Beans (1kg)',
			'slug'        => 'artisan-single-origin-coffee-beans',
			'category'    => 'Grocery',
			'price'       => 24.5,
			'regular'     => 32,
			'stock'       => 55,
			'rating'      => 4.9,
			'reviews'     => 1620,
			'description' => '100% Arabica beans from the high altitudes of Ethiopian highlands. Roasted in small batches with tasting notes of dark chocolate, toasted caramel, and ripe blueberry.',
			'features'    => array( 'Single-origin Arabica altitude 2,100m', 'Small batch artisanal drum roasted', 'Valved foil bag for ultimate aroma preservation' ),
			'specs'       => array(
				'Roast Level'    => 'Medium-Dark',
				'Net Weight'     => '1000g (2.2 lbs)',
				'Flavor Profile' => 'Dark Cacao, Caramelized Honey, Berry',
			),
			'brand'       => 'RoastCraft',
			'tags'        => array( 'coffee', 'beverage', 'organic', 'gourmet' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => true,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-groc-3',
			'name'        => 'Cold-Pressed Extra Virgin Tuscan Olive Oil (750ml)',
			'slug'        => 'cold-pressed-extra-virgin-tuscan-olive-oil',
			'category'    => 'Grocery',
			'price'       => 21.99,
			'regular'     => 29.99,
			'stock'       => 48,
			'rating'      => 4.8,
			'reviews'     => 890,
			'description' => 'Single-estate early harvest Frantoio olives cold-pressed within 6 hours of picking. Delivers a vibrant peppery finish with notes of freshly cut grass and green almonds.',
			'features'    => array( 'Acidity level below 0.2% for highest grade extra virgin quality', 'D.O.P. Certified Protected Origin from Tuscany, Italy', 'UV-protective dark emerald glass bottle' ),
			'specs'       => array(
				'Volume'  => '750ml (25.4 fl oz)',
				'Harvest' => 'Current Single-Estate Fall Harvest',
			),
			'brand'       => 'GreenHarvest',
			'tags'        => array( 'olive-oil', 'organic', 'pantry', 'italian' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-groc-4',
			'name'        => '100% Pure Raw Organic Wildflower Honeycomb Jar (500g)',
			'slug'        => 'pure-raw-organic-wildflower-honeycomb',
			'category'    => 'Grocery',
			'price'       => 18.5,
			'regular'     => 24,
			'stock'       => 35,
			'rating'      => 4.9,
			'reviews'     => 640,
			'description' => 'Unpasteurized and unfiltered raw honeycomb directly from mountain apiaries. Contains natural pollen, propolis, and live enzymes with a delicate floral sweetness.',
			'features'    => array( 'Includes raw edible 100% natural beeswax honeycomb segment', 'Zero added sugars, syrups, or artificial preservatives', 'Sustainably harvested from non-migratory ethical bee farms' ),
			'specs'       => array(
				'Net Weight' => '500g (17.6 oz)',
				'State'      => 'Raw Unfiltered with Comb',
			),
			'brand'       => 'GreenHarvest',
			'tags'        => array( 'honey', 'organic', 'gourmet', 'breakfast' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-sport-1',
			'name'        => 'Professional Hex Rubber Dumbbell Pair (2x 15kg)',
			'slug'        => 'adjustable-hex-rubber-dumbbell-pair',
			'category'    => 'Sports',
			'price'       => 89.99,
			'regular'     => 119.99,
			'stock'       => 25,
			'rating'      => 4.8,
			'reviews'     => 915,
			'description' => 'Professional grade hex dumbbells cast in solid iron with premium vulcanized rubber coating. Features knurled ergonomic chrome steel handles for secure non-slip grip during heavy lifts.',
			'features'    => array( 'Anti-roll hexagon design prevents rolling on floors', 'Heavy-duty odor-free virgin rubber encasing protects flooring', 'Ergonomically curved knurled steel grip' ),
			'specs'       => array(
				'Total Weight'    => '30 kg (66 lbs pair)',
				'Handle Diameter' => '34mm Ergonomic Steel',
				'Coating'         => 'High Density Shock Absorbent Rubber',
			),
			'brand'       => 'ApexFitness',
			'tags'        => array( 'workout', 'dumbbells', 'fitness', 'strength' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-sport-2',
			'name'        => 'Extra Thick Eco-Friendly Alignment Yoga Mat 6mm',
			'slug'        => 'eco-friendly-alignment-yoga-mat',
			'category'    => 'Sports',
			'price'       => 32.99,
			'regular'     => 48,
			'stock'       => 50,
			'rating'      => 4.7,
			'reviews'     => 620,
			'description' => 'Dual-layer non-slip textured TPE yoga mat with laser-engraved alignment guide lines. Provides joint-protecting cushioning while maintaining stable grounding during all yoga poses.',
			'features'    => array( 'Laser-etched body alignment lines to guide posture', 'Non-toxic, PVC-free, latex-free biodegradable TPE', 'Includes complimentary carrying strap and breathable bag' ),
			'specs'       => array(
				'Thickness'  => '6mm High Density Cushion',
				'Dimensions' => '72" L x 26" W (183cm x 66cm)',
				'Weight'     => '950 grams',
			),
			'brand'       => 'ApexFitness',
			'tags'        => array( 'yoga', 'mat', 'pilates', 'fitness' ),
			'colors'      => array( 'Sage Green', 'Teal Mist', 'Dusty Lavender' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-sport-3',
			'name'        => 'Insulated Pro Vacuum 1L Stainless Steel Water Bottle',
			'slug'        => 'insulated-pro-vacuum-stainless-steel-bottle',
			'category'    => 'Sports',
			'price'       => 26.99,
			'regular'     => 38,
			'stock'       => 65,
			'rating'      => 4.9,
			'reviews'     => 1120,
			'description' => 'Double-wall TempShield vacuum insulation keeps beverages ice-cold for up to 24 hours or piping hot for 12 hours. Made from 18/8 pro-grade stainless steel with sweat-free powder coat.',
			'features'    => array( 'TempShield double-wall vacuum temperature lock', 'Pro-grade 18/8 stainless steel eliminates flavor transfer', 'Leakproof Flex Chug cap with wide comfortable carry loop' ),
			'specs'       => array(
				'Volume'     => '32 oz / 1000ml',
				'Insulation' => '24h Cold / 12h Hot',
			),
			'brand'       => 'ApexFitness',
			'tags'        => array( 'bottle', 'hydration', 'sports', 'outdoor' ),
			'colors'      => array( 'Pacific Blue', 'Stone Grey', 'Alpine Green', 'Obsidian Black' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => true,
			'flash_deal'  => false,
			'best_seller' => true,
		),
		array(
			'ref'         => 'prod-sport-4',
			'name'        => 'Precision Ball-Bearing Aluminum Speed Jump Rope',
			'slug'        => 'precision-ball-bearing-speed-jump-rope',
			'category'    => 'Sports',
			'price'       => 19.99,
			'regular'     => 29.99,
			'stock'       => 40,
			'rating'      => 4.8,
			'reviews'     => 430,
			'description' => '360° dual-axis ball bearings deliver frictionless high-speed rotation for double-unders and HIIT conditioning. Anti-kink PVC coated steel cable with knurled CNC aluminum handles.',
			'features'    => array( '360-degree dual high-precision steel ball bearings', 'Ultra-lightweight knurled non-slip CNC aircraft aluminum grip', 'Tool-free adjustable 3-meter kink-free steel cable' ),
			'specs'       => array(
				'Cable Length'    => '3 Meters (10 ft) Fully Adjustable',
				'Handle Material' => 'Anodized Aircraft Aluminum',
			),
			'brand'       => 'ApexFitness',
			'tags'        => array( 'jump-rope', 'cardio', 'crossfit', 'boxing' ),
			'colors'      => array( 'Metallic Red', 'Stealth Black', 'Electric Blue' ),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => false,
			'best_seller' => false,
		),
		array(
			'ref'         => 'prod-sport-5',
			'name'        => 'Heavy-Duty 5-Piece Resistance Exercise Bands Set',
			'slug'        => 'heavy-duty-resistance-exercise-bands-set',
			'category'    => 'Sports',
			'price'       => 24.99,
			'regular'     => 39.99,
			'stock'       => 55,
			'rating'      => 4.8,
			'reviews'     => 780,
			'description' => 'Stackable exercise resistance bands with door anchor, padded handles, ankle straps, and waterproof travel pouch. Resistance levels ranging from 10 lbs to 150 lbs.',
			'features'    => array( '100% natural Malaysian latex tubing with anti-snap nylon sleeve', 'Heavy-duty steel carabiners for multi-band stacking', 'Includes illustrated workout manual with 30 exercises' ),
			'specs'       => array(
				'Max Tension' => 'Up to 150 lbs (68 kg)',
				'Included'    => '5 Tube Bands, 2 Handles, 2 Ankle Straps, 1 Door Anchor, 1 Bag',
			),
			'brand'       => 'ApexFitness',
			'tags'        => array( 'fitness', 'workout', 'resistance-bands', 'gym' ),
			'colors'      => array(),
			'sizes'       => array(),
			'image'       => 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=800&q=80',
			'gallery'     => array( 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80' ),
			'featured'    => false,
			'flash_deal'  => true,
			'best_seller' => false,
		),
	);
}

/**
 * Reviews from the reference application, keyed by product reference.
 *
 * @return array
 */
function marketly_demo_reviews() {
	return array(
		'prod-flash-1' => array(
			array(
				'author' => 'Emily Johnson',
				'rating' => 5,
				'title'  => 'Best smartwatch I have ever owned!',
				'text'   => 'Great products, fast delivery, and excellent customer service. Marketly is my go-to shopping destination! The display on this watch is breathtaking in bright sunlight.',
			),
			array(
				'author' => 'Marcus Vance',
				'rating' => 5,
				'title'  => 'Premium build quality & stellar battery',
				'text'   => 'Battery lasts almost 8 days easily. ECG and fitness metrics are surprisingly pinpoint accurate. Delivery took just 2 days!',
			),
			array(
				'author' => 'Liam Gallagher',
				'rating' => 4,
				'title'  => 'Very solid watch, slight learning curve for app',
				'text'   => 'The hardware is top notch and the OLED screen is super crisp. The companion mobile application had a few sync hiccups at first, but after the firmware update it runs like a charm.',
			),
			array(
				'author' => 'Jessica Chen',
				'rating' => 5,
				'title'  => 'Comfortable silicone strap and accurate sleep tracking',
				'text'   => 'I wear this every night to monitor my sleep cycles and HRV. Super light on the wrist and the fast magnetic charging cable gets it to 100% in under 45 minutes.',
			),
		),
		'prod-feat-1'  => array(
			array(
				'author' => 'David Miller',
				'rating' => 5,
				'title'  => 'Like running on clouds!',
				'text'   => 'Incredibly comfortable for daily 10k runs. Arch support is spot-on and they look sleek with casual denim too.',
			),
			array(
				'author' => 'Rachel Adams',
				'rating' => 4,
				'title'  => 'Great breathability, size up half a size',
				'text'   => 'The knit upper keeps my feet cool during warm morning workouts. Fits slightly snug, so if you are between sizes, go up half a size.',
			),
			array(
				'author' => 'Chris Evans',
				'rating' => 5,
				'title'  => 'Durability has been unmatched after 200 miles',
				'text'   => 'Tread grip on wet asphalt is excellent. Zero fraying around the eyelets.',
			),
		),
		'prod-feat-2'  => array(
			array(
				'author' => 'Samantha Brooks',
				'rating' => 5,
				'title'  => 'Studio level audio isolation',
				'text'   => 'The active noise cancellation creates total silence on noisy airplane flights and subway commutes. The leatherette ear cushions are luxurious.',
			),
			array(
				'author' => 'Tyler Reed',
				'rating' => 4,
				'title'  => 'Crisp bass response and rich soundstage',
				'text'   => 'Audio reproduction across jazz, electronic and podcasts is crystal clear. Transparency mode is very natural.',
			),
		),
		'prod-best-4'  => array(
			array(
				'author' => 'Sophia Laurent',
				'rating' => 5,
				'title'  => 'Elevated our entire living room',
				'text'   => 'The texture of the oatmeal heather fabric is gorgeous and resistant to stains. Assembly took 10 minutes flat. Highly recommend!',
			),
			array(
				'author' => 'Daniel Kim',
				'rating' => 4,
				'title'  => 'Sturdy solid wood legs and plush cushioning',
				'text'   => 'Great minimalist design. Seat cushion is comfortably firm and provides good lumbar support.',
			),
		),
	);
}
