<?php
/**
 * Capabilities — only the site Administrator/Owner may manage properties.
 *
 * The Property post type uses its own capability set (`edit_properties`,
 * `publish_properties`, …) instead of the shared `post` caps. Because those
 * capabilities are granted to the `administrator` role and nothing else,
 * Editors, Authors, Contributors and Subscribers cannot see or touch listings
 * even if they somehow reach wp-admin.
 *
 * @package Haven
 */

defined( 'ABSPATH' ) || exit;

class Haven_Caps {

	/**
	 * Full capability set generated by `map_meta_cap` for the property type.
	 *
	 * @return string[]
	 */
	public static function property_caps() {
		return array(
			'edit_property',
			'read_property',
			'delete_property',
			'edit_properties',
			'edit_others_properties',
			'publish_properties',
			'read_private_properties',
			'delete_properties',
			'delete_private_properties',
			'delete_published_properties',
			'delete_others_properties',
			'edit_private_properties',
			'edit_published_properties',
		);
	}

	/**
	 * Capability set for captured leads (inquiries, consultations, subscribers).
	 *
	 * @return string[]
	 */
	public static function lead_caps() {
		return array(
			'edit_haven_lead',
			'read_haven_lead',
			'delete_haven_lead',
			'edit_haven_leads',
			'edit_others_haven_leads',
			'publish_haven_leads',
			'read_private_haven_leads',
			'delete_haven_leads',
			'delete_private_haven_leads',
			'delete_published_haven_leads',
			'delete_others_haven_leads',
			'edit_private_haven_leads',
			'edit_published_haven_leads',
		);
	}

	/**
	 * Grant every Haven capability to the administrator role.
	 *
	 * Runs on activation, and again whenever the stored version differs, so a
	 * plugin update can add new capabilities without a manual re-activation.
	 */
	public static function grant_to_admins() {
		$roles = apply_filters( 'haven_manager_roles', array( 'administrator' ) );
		$caps  = array_merge( self::property_caps(), self::lead_caps() );

		foreach ( $roles as $role_name ) {
			$role = get_role( $role_name );

			if ( ! $role ) {
				continue;
			}

			foreach ( $caps as $cap ) {
				$role->add_cap( $cap );
			}
		}

		update_option( 'haven_caps_version', HAVEN_CORE_VERSION );
	}

	/**
	 * Re-sync capabilities after a plugin update.
	 */
	public static function maybe_upgrade() {
		if ( get_option( 'haven_caps_version' ) !== HAVEN_CORE_VERSION ) {
			self::grant_to_admins();
		}
	}
}
